project:
  type: website

  preview: 
    port: 5555
    browser: true
    watch-inputs: true
    navigate: true

  render:
    - "*.qmd"
    - "*.md"
    - "!etc/"

  resources:
    - "files/**"
    - "etc/**"

    # Things that need to be at the site root
    - ".htaccess"
    #- "LiveSearchSiteAuth.xml"
    #- "keybase.txt"
    #- "y_key_31e0c4105fc75710.html"
    #- "pgp_ath.asc.txt"

freeze: auto

bibliography: files/bib/references.bib
#csl: files/bib/chicago-author-date.csl

# Metadata stuff
pagetitle: "{{< meta title >}} | Aleksi Knuutila"
description-meta: "Aleksi Knuutila is a Senior Researcher in Sociology at the University of Helsinki"
author-meta: "Aleksi Knuutila"

website:
  title: "Aleksi Knuutila"
  description: "{{< meta description-meta >}}"
  favicon: "/files/favicon-512.png"
  site-url: "https://knuutila.net"
  repo-url: "https://github.com/AleksiKnuutila/personal-quarto-site"

  #google-analytics: ""

  twitter-card: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    card-style: summary_large_image
    creator: "@knuutila"
    site: "@knuutila"

  open-graph: 
    image: "/files/profiles/twitter-card-large.png"
    description: "{{< meta description-meta >}}"
    locale: en_US
  
  navbar:
    pinned: true

    left:
      - text: "About"
        href: "index.qmd"
      - text: "Blog"
        file: blog/index.qmd
      - text: "Research"
        file: research/index.qmd
      - text: "Talks"
        href: "talks/index.qmd"
    
    right:
      - icon: rss
        aria-label: rss
        href: atom.xml
      - icon: envelope
        aria-label: email
        href: "mailto:aleksi.knuutila@helsinki.fi"
      - icon: twitter
        aria-label: twitter
        href: https://twitter.com/knuutila
        rel: me
      #- icon: mastodon
      #  aria-label: mastodon
      #  href: https://fediscience.org/users
      #  rel: me
      - icon: github
        aria-label: github
        href: https://github.com/AleksiKnuutila
        rel: me
  
  page-footer:
    left: |
      <span class="faux-block">{{< fa brands creative-commons >}} {{< var years >}} Aleksi Knuutila</span>
      <span class="faux-block">All content licensed under<br>[{{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}} Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/)</span>      
    #center: |
    #  <span class="faux-block">{{< fa brands orcid >}} <strong>ORCID</strong> [{{< var orcid >}}](https://orcid.org/{{< var orcid >}})</span>
    #  <span class="faux-block">{{< fa key >}} [PGP public key]({{< var pgp.key >}}) &emsp; {{< fa fingerprint >}} Fingerprint:</strong><br><span class="fingerprint">{{< var pgp.fingerprint >}}</span></span>
    right: |
      <span class="faux-block">Made with [Quarto](https://quarto.org/)</span>
      <span class="faux-block">[View the source at {{< fa brands github >}} GitHub]({{< var github-url >}})</span>

format:
  html:
    theme: 
      - html/ath.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true
    highlight-style: monokai
